services:
  - type: web
    name: n8n
    env: docker
    plan: free
    autoDeploy: true
    region: oregon
    dockerfilePath: ./Dockerfile
    envVars:
      - key: N8N_BASIC_AUTH_ACTIVE
        value: "true"
      - key: N8N_BASIC_AUTH_USER
        value: "admin"
      - key: N8N_BASIC_AUTH_PASSWORD
        value: "yourpassword"
      - key: N8N_HOST
        value: "0.0.0.0"
      - key: N8N_PORT
        value: "5678"
      - key: GENERIC_TIMEZONE
        value: "UTC"
    disk:
      name: n8n_data
      mountPath: /home/node/.n8n
      sizeGB: 1
